Fix/adaptation for new search
ostis-ai/scl-machine pull request #42
Opened 2023-01-31 14:32 UTC by kilativ-dotcom

2023-01-31 15:40 UTC, MksmOrlov requested changes

2023-01-31 15:40 UTC, MksmOrlov commented on docs/changelog.md
> +- Add arguments to sub formulas in conjunction and disjunction
```suggestion
- Add arguments to subformulas in conjunction and disjunction
```

2023-01-31 15:40 UTC, MksmOrlov commented on docs/changelog.md
> +- Replaced ms_context with m_memoryCtx in DIA
What is the difference? What bug is it entails

2023-02-04 17:40 UTC, MksmOrlov approved these changes

2023-02-04 17:40 UTC, MksmOrlov commented
Also ask @NikitaZotov for review

2023-02-09 14:56 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/test/units/TestTemplateSearchModule.cpp
>    EXPECT_TRUE(searchResults.size() == 2);
Use EXPECT_EQ instead

2023-02-09 14:56 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/test/units/TestTemplateSearchModule.cpp
> +#include "algorithm"
```suggestion
#include <algorithm>
```

2023-02-09 14:56 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/test/units/TestTemplateSearchModule.cpp
> +  ScAddrVector expectedResults = {
Use ScAddrSet instead

2023-02-21 12:17 UTC, NikitaZotov approved these changes

2023-02-22 16:32 UTC, merged