Feature/solution tree
ostis-ai/scl-machine pull request #43
Opened 2023-02-09 15:52 UTC by kilativ-dotcom

solve issue #39 with parameters in solution tree

2023-02-21 12:22 UTC, NikitaZotov commented
Does this feature work?

2023-02-22 15:48 UTC, MksmOrlov commented
Also update documentation

2023-02-22 15:51 UTC, MksmOrlov commented
Also update documentation and fix typo "applyRile" in file

2023-02-23 12:21 UTC, NikitaZotov approved these changes

2023-03-01 14:18 UTC, MksmOrlov requested changes
Do not delete pdf. Recompile it with the changes in this PR and push it

2023-03-01 14:24 UTC, kilativ-dotcom commented
> Do not delete pdf. Recompile it with the changes in this PR and push it

Deleted pdf by mistake. Now it is back

2023-03-01 14:48 UTC, MksmOrlov requested changes

2023-03-01 14:48 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/generator/SolutionTreeGenerator.cpp
> +  for (const auto & varName: varNames)
Do not use auto for primitives (also strings)
```suggestion
  for (std::string const & varName : varNames)
```

2023-03-01 14:48 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/manager/SolutionTreeManager.cpp
> +bool SolutionTreeManager::checkIfSolutionNodeExists(const ScAddr & rule, ScTemplateParams const & templateParams, std::set<std::string> const & varNames)
```suggestion
bool SolutionTreeManager::checkIfSolutionNodeExists(ScAddr const & rule, ScTemplateParams const & templateParams, std::set<std::string> const & varNames)
```

2023-03-01 14:48 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/searcher/SolutionTreeSearcher.cpp
> +bool SolutionTreeSearcher::checkIfSolutionNodeExists(const ScAddr & rule, ScTemplateParams const & templateParams, std::set<std::string> const & varNames)
const after type everywhere
```suggestion
bool SolutionTreeSearcher::checkIfSolutionNodeExists(ScAddr const & rule, ScTemplateParams const & templateParams, std::set<std::string> const & varNames)
```

2023-03-02 12:40 UTC, merged