Feature/conjunction generation
ostis-ai/scl-machine pull request #44
Opened 2023-02-13 12:17 UTC by kilativ-dotcom

2023-02-21 12:21 UTC, NikitaZotov requested changes

2023-02-21 12:21 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/TemplateExpressionNode.cpp
> +  std::set<std::string> varNames = templateSearcher->getVarNames(formulaTemplate);
```suggestion
  std::set<std::string> const & varNames = templateSearcher->getVarNames(formulaTemplate);
```

2023-02-21 12:21 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/TemplateExpressionNode.cpp
> +        for (const auto & name: varNames)
```suggestion
        for (std::string const & name: varNames)
```

2023-02-21 12:21 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/TemplateExpressionNode.cpp
> +              generationResult.GetReplacements().find(name) != generationResult.GetReplacements().end();
```suggestion
              generationResult.GetReplacements().find(name) != generationResult.GetReplacements().cend();
```

2023-02-21 12:21 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/TemplateExpressionNode.cpp
> +          bool generationHasVar =
```suggestion
          bool const generationHasVar =
```

2023-02-21 12:21 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/TemplateExpressionNode.cpp
> +          bool paramsHaveVar = scTemplateParams.Get(name, outResult);
```suggestion
          bool const paramsHaveVar = scTemplateParams.Get(name, outResult);
```

2023-02-21 12:21 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/test/units/TestComplexFormulas.cpp
> +  SC_LOG_DEBUG("exists = " + to_string(stat(name.c_str(), &buffer) == 0));
Remove it

2023-02-21 12:21 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/test/testStructures/LogicModule/ComplexFormulas/conjunctionInConclusionTest.scs
> +
Remove new lines

2023-02-21 12:21 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/logic/ConjunctionExpressionNode.cpp
> +  for (const auto & operand: operands)
```suggestion
  for (auto const & operand: operands)
```

2023-02-22 15:45 UTC, MksmOrlov approved these changes

2023-02-22 15:45 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/logic/ConjunctionExpressionNode.cpp
> +  for (const auto & operand: operands)
```suggestion
  for (auto const & operand : operands)
```

2023-02-22 15:45 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/logic/TemplateExpressionNode.cpp
> +        for (const auto & name: varNames)
```suggestion
        for (auto const & name : varNames)
```

2023-02-23 12:18 UTC, NikitaZotov approved these changes

2023-02-23 12:32 UTC, merged