[manager] Implement inference manager builder
ostis-ai/scl-machine pull request #46
Opened 2023-03-22 14:15 UTC by MksmOrlov

Менеджер логического вывода конфигурируется двумя сущностями: _TemplateSearcher_ и _FormulasIterationStrategy_. _TemplateSearcher_ определяет поиск в структуре или без структуры, может расширятся указанием структур, в которых **не** должно быть конструкций. _FormulasIterationStrategy_ определяет стратегию применения формул, то есть работа с параметром _Шаблон цели_ (targetTemplate).

2023-03-22 14:29 UTC, NikitaZotov reviewed
Add tests and update documentation, please

2023-03-22 14:46 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/searcher/TemplateSearcherInStructures.cpp
> +      context->HelperSmartSearchTemplate(
```suggestion
      context->HelperSearchTemplate(
```

2023-03-23 10:20 UTC, KovalM requested changes

2023-03-23 10:20 UTC, KovalM commented on problem-solver/cxx/inferenceModule/builder/InferenceManagerBuilderAbstract.hpp
> +class InferenceManagerBuilderAbstract
Why we need abstract builder? I can't think of cases where we need it.

2023-03-23 10:20 UTC, KovalM commented on problem-solver/cxx/inferenceModule/builder/InferenceManagerInputStructuresBuilder.cpp
> +  templateSearcher->setInputStructures(inputStructures);
inputStructures is field of searcher. We don't need to pass it to builder. Just pass to builder searcher with already set structure

2023-03-23 10:20 UTC, KovalM commented on problem-solver/cxx/inferenceModule/director/InferenceManagerDirector.hpp
> +  static InferenceManagerGeneral constructDirectInferenceManagerInputStructuresStrategyAll(
I think we should create builder in method implementation and don't pass it as param

2023-03-23 10:20 UTC, KovalM commented on problem-solver/cxx/inferenceModule/director/InferenceManagerDirector.cpp
> +    ->setTemplateSearcher(new TemplateSearcherInStructures(context))
Let's talk about using smart pointers. We can try approach like here: https://stackoverflow.com/questions/25405034/stdshared-ptr-of-abstract-class-to-instantiate-derived-class

2023-03-23 10:20 UTC, KovalM commented on problem-solver/cxx/inferenceModule/manager/InferenceManagerGeneral.cpp
> +  formulasIterationStrategy = strategy;
What about defaut objects? This is a memory leak

2023-03-24 12:55 UTC, KovalM requested changes

2023-03-24 12:55 UTC, KovalM commented on problem-solver/cxx/inferenceModule/builder/InferenceManagerBuilderAbstract.hpp
> +  //  virtual std::unique_ptr<DirectInferenceManagerGeneral> buildTemplateManager() = 0;
Remove

2023-03-24 12:55 UTC, KovalM commented on problem-solver/cxx/inferenceModule/builder/InferenceManagerBuilderAbstract.hpp
> +
add reset method

2023-03-24 12:55 UTC, KovalM commented on problem-solver/cxx/inferenceModule/manager/InferenceManagerGeneral.cpp
> +  formulasIterationStrategy->setSolutionTreeManager(std::move(solutionTreeManager));
This logic for setup object. It should be done by builder or constructor. We don't need to do it for each call of applyInference

2023-03-28 08:18 UTC, KovalM commented
viewed. Interfaces Approved

2023-03-31 10:22 UTC, MksmOrlov commented
ImplicationExpressionNode::compute call TemplateExpressionNode::compute to get premise replacements.
Then  ImplicationExpressionNode call ImplicationExpressionNode::generate with found replacements.
`generate(Replacements & replacements)`  generate has  Replacements as an input and convert it

2023-04-28 11:01 UTC, KovalM requested changes

2023-04-29 08:32 UTC, KovalM requested changes

2023-04-29 08:32 UTC, KovalM commented on problem-solver/cxx/inferenceModule/manager/TemplateManager.cpp
> +    // TODO(MksmOrlov): Почему итерируемся по классам и для них ищем есть ли аргумент, а не от аргумента ищем, есть ли соответствующий класс
Use English

2023-04-29 08:32 UTC, KovalM commented on problem-solver/cxx/inferenceModule/manager/TemplateManager.cpp
> +    // TODO(MksmOrlov): Почему итерируемся по классам и для них ищем есть ли аргумент, а не от аргумента ищем, есть ли соответствующий класс
As I see, we start iteration from argument(var)

2023-04-29 08:32 UTC, KovalM commented on problem-solver/cxx/inferenceModule/manager/TemplateManagerAbstract.hpp
> +    generateOnlyFirst = true;
Can we replace flags by different implementations?

2023-04-29 08:32 UTC, KovalM commented on problem-solver/cxx/inferenceModule/manager/InferenceManagerGeneral.hpp
> +  ScAddr applyInference(ScAddr const & formulasSet);
In some cases we need to use the same manger many times for the same setting but for different arguments. Now we need to create new manger for each arguments set. Can we make arguments this method's param

2023-05-11 07:44 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/classifier/FormulaClassifier.cpp
> +  // TODO(MksmOrlov): maybe we need just to check element type (struct) with/without variables
add after `bool isAtomicFormula =
      ms_context->HelperCheckEdge(InferenceKeynodes::atomic_logical_formula, formula, ScType::EdgeAccessConstPosPerm);` additional checking if there is any variable in formula (if isAtomicFormula is false). So we would'n need to specify sc-structure necessarily, we get this knowledge from the sc-structure content

2023-05-11 14:55 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/strategy/FormulasIterationStrategyTarget.cpp
> +          templateSearcher->searchTemplate(targetStructure, templateParams, varNames, result);
Depends on template searcher. TemplateSearcherInStructures is always smart (stops at first), TemplateSearcher searchs all results.
We must implement configuration for using smart search template or default

2023-05-11 14:58 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/strategy/FormulasIterationStrategyTarget.cpp
> +        solutionTreeManager->addNode(formula, ReplacementsUtils::getReplacementsToScTemplateParams(
Yes, but in strategy all only. I've made it now also for the strategy target

2023-05-11 15:01 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/manager/TemplateManager.cpp
> +    // TODO(MksmOrlov): Почему итерируемся по классам и для них ищем есть ли аргумент, а не от аргумента ищем, есть ли соответствующий класс
1st cycle level is about vars, 2nd level is about classes and the most nested 3rd level is about arguments. I suggest to replace 1st and 3rd levels

2023-05-11 15:10 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/manager/InferenceManagerGeneral.hpp
> +  ScAddr applyInference(ScAddr const & formulasSet);
hmm for the other hand in some cases we need to use the same manager with same arguments, same formulas but different input structures, so we need to create new manager for each input structures set. I will think about it

2023-05-17 15:20 UTC, KovalM commented on docs/changelog.md
> +- Template searcher in structures
```suggestion
- Inference in structures
```

2023-05-17 15:46 UTC, KovalM requested changes

2023-05-17 15:46 UTC, KovalM commented on problem-solver/cxx/inferenceModule/inferenceConfig/InferenceConfig.hpp
> +struct InferenceFlowConfig
```suggestion
struct InferenceConfig
```

2023-05-17 15:46 UTC, KovalM commented on problem-solver/cxx/inferenceModule/inferenceConfig/InferenceConfig.hpp
> +struct InferenceParamsConfig
```suggestion
struct InferenceParams
```

2023-05-17 15:46 UTC, KovalM commented on problem-solver/cxx/inferenceModule/manager/DirectInferenceManager.cpp
> +  InferenceFlowConfig const & inferenceFlowConfig{true, true, false};
I think configs should not be flags, configs should be enum elements

2023-05-17 15:46 UTC, KovalM commented on problem-solver/cxx/inferenceModule/manager/DirectInferenceManager.cpp
>  ScAddr DirectInferenceManager::applyInference(
Let's discuss about this class

2023-05-18 07:15 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/inferenceConfig/InferenceConfig.hpp
> +struct InferenceFlowConfig
Because we need just to store some data, there are no methods. 
[Google C++ code style: Struct vs Classes](https://google.github.io/styleguide/cppguide.html#Structs_vs._Classes)

2023-05-18 14:30 UTC, KovalM requested changes

2023-05-18 14:30 UTC, KovalM commented on problem-solver/cxx/inferenceModule/manager/inferenceManager/DirectInferenceManagerTarget.hpp
> +  void setTargetStructure(ScAddr const & otherTargetStructure);
why is it public?

2023-05-19 12:20 UTC, KovalM requested changes

2023-05-19 12:20 UTC, KovalM commented on problem-solver/cxx/inferenceModule/inferenceConfig/InferenceConfig.hpp
> +enum ReplacementsUsingType
Let's discuss about convention for enums. Now it is not accorded google convention: https://google.github.io/styleguide/cppguide.html#Enumerator_Names

2023-05-20 07:20 UTC, KovalM approved these changes

2023-05-20 07:45 UTC, merged