Feat/use sc addr in replacements
ostis-ai/scl-machine pull request #57
Opened 2024-01-05 08:50 UTC by kilativ-dotcom

2024-01-06 13:50 UTC, MksmOrlov requested changes
Write about replacements in scn-docunentation

2024-01-06 13:50 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/generator/SolutionTreeGenerator.hpp
> +#include "utils/ReplacementsUtils.hpp"
You don't need it here

2024-01-06 13:50 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/searcher/templateSearcher/TemplateSearcherAbstract.cpp
> +    variables.insert(formulaVariablesIterator->Get(2));
Why don't you add variables only with identifiers? Do you need unnamed variables?

2024-01-06 13:50 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/searcher/solutionTreeSearcher/SolutionTreeSearcher.cpp
> +      std::string pair_alias = replacement_for_alias + to_string(variable.Hash());
use camelCase

2024-01-06 13:50 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/searcher/templateSearcher/TemplateSearcherAbstract.cpp
> +      context->Iterator3(formula, ScType::EdgeAccessConstPosPerm, ScType::Var);
you can use iterator utils get all with type to get the same result

2024-01-06 13:50 UTC, MksmOrlov commented on problem-solver/cxx/inferenceModule/manager/templateManager/TemplateManager.cpp
> +    ScAddr const & var = varIterator->Get(2);
Declare variable outside the cycle and name it as `variable`

2024-01-22 09:03 UTC, kilativ-dotcom commented on problem-solver/cxx/inferenceModule/searcher/templateSearcher/TemplateSearcherAbstract.cpp
> +    variables.insert(formulaVariablesIterator->Get(2));
there may be formulas that have same unnamed variable in different atomic logical formulas

2024-01-22 09:32 UTC, kilativ-dotcom commented on problem-solver/cxx/inferenceModule/searcher/templateSearcher/TemplateSearcherAbstract.cpp
> +      context->Iterator3(formula, ScType::EdgeAccessConstPosPerm, ScType::Var);
I can do that, but getAllWithType creates temporary vector and insertions in this vector take time+memory

2024-01-22 10:00 UTC, kilativ-dotcom commented on problem-solver/cxx/inferenceModule/manager/templateManager/TemplateManager.cpp
> +    ScAddr const & var = varIterator->Get(2);
I think it's better to declare this variable as const inside the loop. there may be some compiler optimizations for const variables

2024-01-22 10:53 UTC, MksmOrlov approved these changes
Check unresolved comment

2024-01-22 10:53 UTC, MksmOrlov commented on docs/scl-machine.tex
> +\scntext{примечание}{Является однозначным соответствием между множеством sc-переменных и множеством кортежей sc-констант. Областью отправления соответствия является множество всех sc-переменных атома
```suggestion
\scntext{примечание}{Является взаимно однозначным соответствием между множеством sc-переменных и множеством кортежей sc-констант. Областью отправления соответствия является множество всех sc-переменных атомарной логической формулы, а соответствующим определённой sc-переменной элементом из области прибытия соответствия является кортеж, элементы которого при подстановке их в атомарную логическую формулу на место этой sc-переменнной делают формулу истинной. Корректно составленные подстановки имеют равномощные множества в области прибытия. Таким образом, элементы области прибытия могут образовывать прямоугольную матрицу. В этой матрице по колонкам для каждой переменной хранятся подстановки, при замене каждой sc-переменной на которую атомарная логическая формула становится истинной.}
```

2024-01-22 16:42 UTC, merged