Add solution removal agent
ostis-ai/scl-machine pull request #65
Opened 2024-05-07 09:18 UTC by kilativ-dotcom

2024-05-07 12:01 UTC, MksmOrlov requested changes

2024-05-07 16:57 UTC, kilativ-dotcom commented on problem-solver/cxx/solutionModule/manager/DeleteSolutionManager.cpp
> +ScAddrList DeleteSolutionManager::getListFromSet(ScAddr const & set) const
looks like sc-machine is unable to iterate over Iterator3 while removing nodes that are at iterator->Get(2)

2024-05-10 15:45 UTC, MksmOrlov approved these changes

2024-05-10 15:45 UTC, MksmOrlov commented on docs/scl-machine.tex
> +		%\scnrelfrom{описание примера}{\scnfileimage[28em]{images/target_template.png}}
Remove comment or uncomment comment?

2024-05-10 15:45 UTC, MksmOrlov commented on problem-solver/cxx/solutionModule/manager/DeleteSolutionManager.cpp
> +DeleteSolutionManager::DeleteSolutionManager(ScMemoryContext * context)
And what?

2024-05-10 15:45 UTC, MksmOrlov commented on problem-solver/cxx/solutionModule/manager/DeleteSolutionManager.hpp
> +  ScMemoryContext * context;
And what if all will go to the window jumping hobby?

2024-05-15 09:15 UTC, merged