Remove codegen
ostis-ai/scl-machine pull request #72
Opened 2024-09-03 14:20 UTC by kilativ-dotcom

2024-09-03 15:27 UTC, NikitaZotov requested changes
It is the first part of my review

2024-09-03 15:27 UTC, NikitaZotov commented on docs/changelog.md
>  - Changed condition for applying generation(generate if this rule with this parameters wasn't applied yet)
Add breaking changes about changed primary initiation condition of agents

2024-09-03 15:27 UTC, NikitaZotov commented on docs/changelog.md
>  ### Removed
Add line about fixed tests

2024-09-03 15:27 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/CMakeLists.txt
> +include_directories(${CMAKE_CURRENT_LIST_DIR} ${SC_MEMORY_SRC} ${SC_KPM_SRC})
We should use target_include_directories instead. Don't use include_directories, it includes source globally

2024-09-03 15:27 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/CMakeLists.txt
>  target_link_libraries(inferenceModule sc-memory sc-agents-common)
```suggestion
target_link_libraries(inferenceModule 
     LINK_PRIVATE sc-memory
     LINK_PRIVATE sc-agents-common
)
```

2024-09-03 15:27 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.cpp
>  #include <sc-agents-common/utils/IteratorUtils.hpp>
Please, sort includes everywhere

2024-09-03 15:27 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.cpp
> +  ScAddr const inputStructure = action.GetArgument(4);
```suggestion
  auto const [targetStructure, formulasSet, arguments, inputStructure] = action.GetArguments<4>();
```

2024-09-03 15:27 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.cpp
> +  if (!targetStructure.IsValid() || !utils::IteratorUtils::getAnyFromSet(&m_context, targetStructure).IsValid())
```suggestion
  ScAddr const & elementAddr = utils::IteratorUtils::getAnyFromSet(&m_context, targetStructure);
  if (!targetStructure.IsValid() || !elementAddr.IsValid())
```

2024-09-03 15:27 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.cpp
> +  if (!targetStructure.IsValid() || !utils::IteratorUtils::getAnyFromSet(&m_context, targetStructure).IsValid())
Don't use function calls in a row, it's worse for debugging

2024-09-03 15:27 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.cpp
> +  if (!formulasSet.IsValid() || !utils::IteratorUtils::getAnyFromSet(&m_context, formulasSet).IsValid())
It's the same here

2024-09-03 15:27 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.cpp
> +  if (!formulasSet.IsValid() || !utils::IteratorUtils::getAnyFromSet(&m_context, formulasSet).IsValid())
Check everywhere

2024-09-03 15:27 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.cpp
> +    return action.FinishUnsuccessfully();
Shouldn't be action.FinishWithError() here?

2024-09-03 15:27 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.hpp
> +#include "sc-memory/sc_agent.hpp"
```suggestion
#include <sc-memory/sc_agent.hpp>
```

2024-09-03 15:27 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.hpp
> +#include "sc-memory/sc_agent.hpp"
Fix everywhere

2024-09-03 15:34 UTC, kilativ-dotcom commented on docs/changelog.md
>  ### Removed
I haven't fixed any tests

2024-09-03 15:52 UTC, kilativ-dotcom commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.cpp
> +  if (!targetStructure.IsValid() || !utils::IteratorUtils::getAnyFromSet(&m_context, targetStructure).IsValid())
if I do as you suggest then there will be iterator3->Next() call before targetStructure is checked for validity, I added usage of ConvertToSet/Structure but it still has 2 method calls in a row

2024-09-03 15:59 UTC, kilativ-dotcom commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.cpp
> +    return action.FinishUnsuccessfully();
in an ideal world it should be checked by initiationConditionTemplate, I don't see why this situation should be considered as error

2024-09-04 20:52 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.cpp
> +  if (!targetStructure.IsValid() || !utils::IteratorUtils::getAnyFromSet(&m_context, targetStructure).IsValid())
`if (!targetStructure.IsValid())
 ...
 
 ScAddr const & elementAddr = utils::IteratorUtils::getAnyFromSet(&m_context, targetStructure);
 if (!elementAddr.IsValid())
 ...
`

2024-09-04 20:54 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.cpp
> +    return action.FinishUnsuccessfully();
In that case, is there a need for verification here?

2024-09-04 21:11 UTC, NikitaZotov requested changes

2024-09-04 21:11 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/test/tests.cmake
> +		INCLUDES ${SC_MEMORY_SRC}/tests/sc-memory/_test ${SC_MACHINE_ROOT}/sc-tools/sc-builder/src ${CMAKE_CURRENT_LIST_DIR}/..)
It's bad to do that, use in the CMakeLists.txt of inferenceModule in target_include_directories PUBLIC instead of PRIVATE. Otherwise now everyone who wants to use scl-machine will have to write this include (that you wrote in tests) in his own place. After the transition to the new build system, we will fix it.

2024-09-04 21:11 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/test/units/TestComplexFormulas.cpp
> +  ScAgentContext context;
Why do you not use m_ctx? It is an object of `ScAgentContext`

2024-09-04 21:11 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/test/units/TestComplexFormulas.cpp
> +  ScAction action = context.ConvertToAction(context.HelperFindBySystemIdtf(ACTION_IDENTIFIER));
I don't like multiple calls in one line

2024-09-04 21:11 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/test/units/TestLogicModuleArguments.cpp
> +  ScAddr solution = utils::IteratorUtils::getAnyFromSet(&context, result);
```suggestion
  ScAddr solution = utils::IteratorUtils::getAnyFromSet(&context, result);
  EXPECT_TRUE(solution.IsValid());
```

2024-09-04 21:11 UTC, NikitaZotov commented on problem-solver/cxx/solutionModule/agent/DeleteSolutionAgent.cpp
> +    if (m_context.IsElement(solution) == SC_FALSE)
```suggestion
    if (!m_context.IsElement(solution))
```

2024-09-04 21:11 UTC, NikitaZotov commented on problem-solver/cxx/solutionModule/agent/DeleteSolutionAgent.cpp
> +    if (m_context.IsElement(solution) == SC_FALSE)
Shouldn't be IsValid here?

2024-09-04 21:11 UTC, NikitaZotov commented on problem-solver/cxx/solutionModule/agent/DeleteSolutionAgent.cpp
> +    return action.FinishUnsuccessfully();
```suggestion
    return action.FinishWithError();
```

2024-09-04 21:11 UTC, NikitaZotov commented on problem-solver/cxx/solutionModule/agent/DeleteSolutionAgent.cpp
> +    return action.FinishUnsuccessfully();
I think it's more appropriate here

2024-09-04 21:11 UTC, NikitaZotov commented on problem-solver/cxx/solutionModule/test/tests.cmake
> +		INCLUDES ${SC_MEMORY_SRC}/tests/sc-memory/_test ${SC_MACHINE_ROOT}/sc-tools/sc-builder/src ${CMAKE_CURRENT_LIST_DIR}/..)
That's what I've been saying

2024-09-05 06:55 UTC, kilativ-dotcom commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.cpp
> +    return action.FinishUnsuccessfully();
sc-machine doesn't have a logic that checks if some agent did start to perform an action or not(action_performed can be used for that but it isn't used) so currently there should be a logic in agents that somehow marks action as impossible to be performed so other agents wouldn't wait for action_direct_inference finish for some WAIT_TIME

2024-09-05 06:56 UTC, kilativ-dotcom commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.cpp
> +    return action.FinishUnsuccessfully();
yes, verification should be here

2024-09-05 07:03 UTC, kilativ-dotcom commented on problem-solver/cxx/inferenceModule/test/units/TestComplexFormulas.cpp
> +  ScAgentContext context;
these tests weren't written by me, someone decided to do that

2024-09-05 07:16 UTC, kilativ-dotcom commented on problem-solver/cxx/solutionModule/agent/DeleteSolutionAgent.cpp
> +    if (m_context.IsElement(solution) == SC_FALSE)
no, this place is sus, action may be initiated two times and race condition issues may occur

2024-09-10 13:08 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.cpp
> +  ScSet const & scSet = m_context.ConvertToSet(setAddr);
```suggestion
  ScSet const & set = m_context.ConvertToSet(setAddr);
```

2024-09-10 13:12 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/test/units/TestComplexFormulas.cpp
> +  ScAgentContext context;
Okay, you will do this in separate PR

2024-09-10 13:14 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/generator/SolutionTreeGenerator.hpp
> +#include <queue>
Can you sort includes here?

You changed these lines. I think you can refactor it now

2024-09-11 09:08 UTC, kilativ-dotcom commented on problem-solver/cxx/inferenceModule/agent/DirectInferenceAgent.cpp
> +  ScSet const & scSet = m_context.ConvertToSet(setAddr);
set is something used by std, I don't think that it is good to use such name for a variable

2024-09-11 09:12 UTC, kilativ-dotcom commented on problem-solver/cxx/inferenceModule/generator/SolutionTreeGenerator.hpp
> +#include <queue>
where can I find the rule that you've used to write your suggestion?
I did use sc-machine codestyle from https://ostis-ai.github.io/sc-machine/dev/codestyle/ where it is saying about 'Order of directories in includes: current_dir/current_file.hpp, other includes from the same dir, includes from other dirs sorted by name.'

2024-09-22 10:57 UTC, NikitaZotov approved these changes

2024-09-23 08:10 UTC, merged