Remove deprecated types
ostis-ai/scl-machine pull request #74
Opened 2024-10-01 14:40 UTC by kilativ-dotcom

2024-10-03 09:16 UTC, NikitaZotov requested changes

2024-10-03 09:16 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/generator/SolutionTreeGenerator.cpp
> +      ms_context->GenerateConnector(ScType::ConstTempPosArc, variable, replacement);
I think we can specify actuality here

2024-10-03 09:16 UTC, NikitaZotov commented on problem-solver/cxx/inferenceModule/generator/SolutionTreeGenerator.cpp
> +      ms_context->GenerateConnector(ScType::ConstTempPosArc, variable, replacement);
Resee everywhere please

2024-10-03 09:16 UTC, NikitaZotov commented on problem-solver/cxx/solutionModule/manager/DeleteSolutionManager.hpp
> +  void deleteConnectors(ScAddr const & source, ScType const & connectorType, ScAddr const & target) const;
```suggestion
  void eraseConnectors(ScAddr const & source, ScType const & connectorType, ScAddr const & target) const;
```

2024-10-03 09:16 UTC, NikitaZotov commented on problem-solver/cxx/solutionModule/manager/DeleteSolutionManager.hpp
> +  void deleteConnectors(ScAddr const & source, ScType const & connectorType, ScAddr const & target) const;
check everywhere such prefixes as create, generate, erase, delete, remove, get, search, find

2024-10-04 06:18 UTC, kilativ-dotcom commented on problem-solver/cxx/inferenceModule/generator/SolutionTreeGenerator.cpp
> +      ms_context->GenerateConnector(ScType::ConstTempPosArc, variable, replacement);
I don't think so
for one formula this substitution is actual, but there is a lot of solution trees in the kb and variables may have different substitutions at every formula usage

2024-10-07 07:24 UTC, NikitaZotov approved these changes

2024-10-07 08:01 UTC, merged