Update docs
ostis-ai/scl-machine pull request #9
Opened 2022-10-24 16:53 UTC by SHtress

2022-10-26 12:38 UTC, MksmOrlov requested changes
How to name branches?

2022-10-26 12:38 UTC, MksmOrlov commented on docs/dev/codestyle.md
> +  * `SC_LOG_INFO_COLOR(msg, color)` - print colored info message. Look color constants in `ScConsole::Color`
Добавь точку с запятой в конце

2022-10-26 12:38 UTC, MksmOrlov commented on docs/dev/pr.md
> +  * `[scripts]` - updates in the `sc-machine/scripts` files
```suggestion
  * `[scripts]` - updates in the `scl-machine/scripts` files
```

2022-10-26 12:38 UTC, MksmOrlov commented on docs/dev/pr.md
> +[kpm][search] Relation type check added
there is no kpm and cpp

2022-10-26 12:38 UTC, MksmOrlov commented on docs/dev/pr.md
> +
Add smth as [inference] or [dia] [ria]. Tag to develop inference agents logic

2022-10-26 14:33 UTC, MksmOrlov approved these changes

2022-10-26 16:51 UTC, AlexandrZagorskiy requested changes

2022-10-26 16:51 UTC, AlexandrZagorskiy commented on docs/dev/git-workflow.md
> +  * use `git rebase` instead of `merge`
when I should use rebase instead of merge?

2022-10-26 16:51 UTC, AlexandrZagorskiy commented on docs/dev/pr.md
> +  * `[ria]` - changes in reverse inference agent; (or [iia] - changes in inverse/indirect inference)
Better to remove any choices, this way will be more confusing

2022-10-31 08:54 UTC, MksmOrlov approved these changes

2022-10-31 08:54 UTC, MksmOrlov commented on docs/changelog.md
> +- Add clang format check
move to the top of the "Added" section

2022-10-31 08:58 UTC, AlexandrZagorskiy approved these changes

2022-10-31 09:00 UTC, merged